### PR TITLE
synchrona rev b fixes and enhancements

### PR DESCRIPTION
**Pull request by nunojsa**
This PR adds fixes and enhancements/cleanups.  The most important ones are in the first patches that fix all the issues related with wrong values being displayed in GUI and also fixes values being applied in the wrong devicetree nodes.

The rest are more improvements, some code cleanup and also some cleanup on the installation. Note that, for now, we are already disabling openvpn and adblock from being installed. Installing with `curl -sL https://raw.githubusercontent.com/analogdevicesinc/raspap-webgui/synchrona_revB/installers/raspbian.sh | bash -s -- -y --repo analogdevicesinc/raspap-webgui --branch "synchrona_revB"` (this command will naturally work only after this PR gets merged) should not include adblock and openvpn.

### CODE REVIEW

**Comment by nunojsa** [comment]
v2:

 * Always reinstall latest adidt;
 * Refactored uninstall (warning log and added adidt)

**Comment by nunojsa** [comment]
v3:

* Don't remove the overlay when stopping the job. This would prevent us from `poweroff`...

**Review by mhennerich — APPROVED** [review]

**Comment by nunojsa** [comment]
let's hold merging for now as I still need to test the last commits I added...

**Comment by nunojsa** [comment]
v4:
 
* Remove synchrona packages on uninstall;
* Remove calls to (and the script) to rebind.sh;
* use $apt_options (from the main script) when installing things;
* Remove rpi-ad9545-hmc7044.dtbo and just use the one on the kuiper image;
* Fix vcxo selection and remove set_vcxo_pin.sh script;
* Disable the hotspot and wificlient services;
* Fix dependency on installation path;
* Blacklist wifi module;
* Call reload_dtb.sh script from php script.

**Pull request merged**
